-- Tabla de Ubicaciones
INSERT INTO ubicaciones (ubicacion) VALUES
('Amazonas - Chachapoyas'),
('<Por ingresar lugar>'),
('Amazonas - Bagua'),
('Amazonas - Bongara'),
('Amazonas - Condorcanqui'),
('Amazonas - Luya'),
('Amazonas - Rodríguez de Mendoza'),
('Amazonas - Utcubamba'),
('Áncash - Huaraz'),
('Áncash - Aija'),
('Áncash - Antonio Raimondi'),
('Áncash - Asunción'),
('Áncash - Bolognesi'),
('Áncash - Carhuaz'),
('Áncash - Carlos Fermín Fitzcarrald'),
('Áncash - Casma'),
('Áncash - Corongo'),
('Áncash - Huari'),
('Áncash - Huarmey'),
('Áncash - Huaylas'),
('Áncash - Mariscal Luzuriaga'),
('Áncash - Ocros'),
('Áncash - Pallasca'),
('Áncash - Pomabamba'),
('Áncash - Recuay'),
('Áncash - Santa'),
('Áncash - Sihuas'),
('Áncash - Yungay'),
('Apurímac - Abancay'),
('Apurímac - Andahuaylas'),
('Apurímac - Antabamba'),
('Apurímac - Aymaraes'),
('Apurímac - Cotabambas'),
('Apurímac - Chincheros'),
('Apurímac - Grau'),
('Arequipa - Arequipa'),
('Arequipa - Camaná'),
('Arequipa - Caravelí'),
('Arequipa - Castilla'),
('Arequipa - Caylloma'),
('Arequipa - Condesuyos'),
('Arequipa - Islay'),
('Arequipa - La Unión'),
('Ayacucho - Huamanga'),
('Ayacucho - Cangallo'),
('Ayacucho - Huanca Sancos'),
('Ayacucho - Huanta'),
('Ayacucho - La Mar'),
('Ayacucho - Lucanas'),
('Ayacucho - Parinacochas'),
('Ayacucho - Páucar del Sara Sara'),
('Ayacucho - Sucre'),
('Ayacucho - Víctor Fajardo'),
('Ayacucho - Vilcashuamán'),
('Cajamarca - Cajamarca'),
('Cajamarca - Cajabamba'),
('Cajamarca - Celendín'),
('Cajamarca - Chota'),
('Cajamarca - Contumazá'),
('Cajamarca - Cutervo'),
('Cajamarca - Hualgayoc'),
('Cajamarca - Jaén'),
('Cajamarca - San Ignacio'),
('Cajamarca - San Marcos'),
('Cajamarca - San Miguel'),
('Cajamarca - San Pablo'),
('Cajamarca - Santa Cruz'),
('Callao - Callao'),
('Cusco - Cuzco'),
('Cusco - Acomayo'),
('Cusco - Anta'),
('Cusco - Calca'),
('Cusco - Canas'),
('Cusco - Canchis'),
('Cusco - Chumbivilcas'),
('Cusco - Espinar'),
('Cusco - La Convención'),
('Cusco - Paruro'),
('Cusco - Paucartambo'),
('Cusco - Quispicanchi'),
('Cusco - Urubamba'),
('Huancavelica - Huancavelica'),
('Huancavelica - Acobamba'),
('Huancavelica - Angaraes'),
('Huancavelica - Castrovirreyna'),
('Huancavelica - Churcampa'),
('Huancavelica - Huaytará'),
('Huancavelica - Tayacaja'),
('Huanuco - Huánuco'),
('Huanuco - Ambo'),
('Huanuco - Dos de Mayo'),
('Huanuco - Huacaybamba'),
('Huanuco - Huamalíes'),
('Huanuco - Leoncio Prado'),
('Huanuco - Marañón'),
('Huanuco - Pachitea'),
('Huanuco - Puerto Inca'),
('Huanuco - Lauricocha'),
('Huanuco - Yarowilca'),
('Ica - Ica'),
('Ica - Chincha'),
('ca - Nazca'),
('Ica - Palpa'),
('Ica - Pisco'),
('Junín - Huancayo'),
('Junín - Chanchamayo'),
('Junín - Chupaca'),
('Junín - Concepción'),
('Junín - Jauja'),
('Junín - Junín'),
('Junín - Satipo'),
('Junín - Tarma'),
('Junín - Yauli'),
('La Libertad - Trujillo'),
('La Libertad - Ascope'),
('La Libertad - Bolívar'),
('La Libertad - Chepén'),
('La Libertad - Gran Chimú'),
('La Libertad - Julcán'),
('La Libertad - Otuzco'),
('La Libertad - Pacasmayo'),
('La Libertad - Pataz'),
('La Libertad - Sánchez Carrión'),
('La Libertad - Santiago de Chuco'),
('La Libertad - Virú'),
('Lambayeque - Chiclayo'),
('Lambayeque - Ferreñafe'),
('Lambayeque - Lambayeque'),
('Lima Metropolitana - Lima'),
('Lima - Huaura'),
('Lima - Barranca'),
('Lima - Cajatambo'),
('Lima - Canta'),
('Lima - Cañete'),
('Lima - Huaral'),
('Lima - Huarochirí'),
('Lima - Oyón'),
('Lima - Yauyos'),
('Loreto - Maynas'),
('Loreto - Alto Amazonas'),
('Loreto - Datem del Marañón'),
('Loreto - Loreto'),
('Loreto - Mariscal Ramón Castilla'),
('Loreto - Putumayo'),
('Loreto - Requena'),
('Loreto - Ucayali'),
('Madre de Dios - Tambopata'),
('Madre de Dios - Manu'),
('Madre de Dios - Tahuamanu'),
('Moquegua - Mariscal Nieto'),
('Moquegua - General Sánchez Cerro'),
('Moquegua - Ilo'),
('Pasco - Pasco'),
('Pasco - Daniel Alcides Carrión'),
('Pasco - Oxapampa'),
('Piura - Piura'),
('Piura - Ayabaca'),
('Piura - Huancabamba'),
('Piura - Morropón'),
('Piura - Paita'),
('Piura - Sechura'),
('Piura - Sullana'),
('Piura - Talara'),
('Puno - Puno'),
('Puno - Azángaro'),
('Puno - Carabaya'),
('Puno - Chucuito'),
('Puno - El Collao'),
('Puno - Huancané'),
('Puno - Lampa'),
('Puno - Melgar'),
('Puno - Moho'),
('Puno - San Antonio de Putina'),
('Puno - San Román'),
('Puno - Sandia'),
('Puno - Yunguyo'),
('San Martín - Moyobambav'),
('San Martín - Bellavista'),
('San Martín - El Dorado'),
('San Martín - Huallaga'),
('San Martín - Lamas'),
('San Martín - Mariscal Cáceres'),
('San Martín - Picota'),
('San Martín - Rioja'),
('San Martín - San Martín'),
('San Martín - Tocache'),
('Tacna - Tacna'),
('Tacna - Candarave'),
('Tacna - Jorge Basadre'),
('Tacna - Tarata'),
('Tumbes - Tumbes'),
('Tumbes - Contralmirante Villar'),
('Tumbes - Zarumilla'),
('Ucayali - Coronel Portillo'),
('Ucayali - Atalaya'),
('Ucayali - Padre Abad'),
('Ucayali - Purús');